Stack Navigation & Home Screen Style
InfernoRed/ContentAuthCamera pull request #2
Opened 2024-05-07 03:43 UTC by ccspart2

Changes:

1) Removed the Tab navigation from the scaffold code. It was replaced by a simple Stack navigation.
2) Added some color and style to the homeScreen.

2024-05-07 15:54 UTC, keithrfung requested changes
I would shift some of those constants such as fontSize, routes, and colors to a theme and start strong that way. Those are such hard cleanup later. It forces consistency too. There are multiple options on how to handle that combo of theming, constants, and componentization.

Strongly consider getting these in ASAP:
- Autoformatting
- Linting
- strings file for i18n
- Pipeline

2024-05-07 15:54 UTC, keithrfung commented on src/app/screens/HomeScreen.tsx
> +        <Link href="/screens/CameraScreen" asChild>
I def would avoid having links directly like this. I usually export them to a string list or export a constant from the file. 

I'd make some `navigation` or `routes` folder and dump these in or export at the top level with an `index.ts` aka barrel file

2024-05-07 15:54 UTC, keithrfung commented on src/app/screens/HomeScreen.tsx
> +        source={require("@/src/assets/images/background.png")}
I believe you should be able to do this with an import. Was that not working? `require` is the older version of `import`.

2024-05-07 15:54 UTC, keithrfung commented on src/app/screens/HomeScreen.tsx
> +          <Pressable style={styles.button} onPress={() => {}}>
I would not just throw in an empty function here. Make a constant.

2024-05-07 15:54 UTC, keithrfung commented on src/app/screens/HomeScreen.tsx
> +  button: {
The button should be componentized or themed. You may use this button style again.

2024-05-07 16:03 UTC, keithrfung commented on src/app/index.tsx
> +export default function HomeScreenContainer() {
You may not need this container here since the original HomeScreen is a function. I would do a reexport if it allows you

`export { HomeScreen as default } from "@/src/app/screens/HomeScreen";`

Then it can also be a `.ts` file or a barrel file. This way you're actually making a container

2024-05-08 01:15 UTC, ccspart2 commented on src/app/screens/HomeScreen.tsx
> +        source={require("@/src/assets/images/background.png")}
Done

2024-05-08 01:19 UTC, ccspart2 commented on src/app/screens/HomeScreen.tsx
> +          <Pressable style={styles.button} onPress={() => {}}>
Added the const empty functions

2024-05-08 01:50 UTC, ccspart2 commented on src/app/screens/HomeScreen.tsx
> +  button: {
done

2024-05-08 01:52 UTC, ccspart2 commented on src/app/index.tsx
> +export default function HomeScreenContainer() {
for me to understand it a little bit better will keep it but renamed as App.

2024-05-08 16:22 UTC, merged